# Generated by Django 5.1 on 2024-09-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_tarefa",
                    models.CharField(
                        choices=[("R", "Recorrente"), ("U", "Única")], max_length=1
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("frequencia", models.DateTimeField(blank=True)),
                ("termino_tarefa", models.DateTimeField(null=True)),
            ],
        ),
    ]
