# Generated by Django 5.1 on 2024-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="horario",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="frequencia",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="termino_tarefa",
            field=models.DateField(null=True),
        ),
    ]
